### PR TITLE
Adding Dutch Translation

### PR DESCRIPTION
**Pull request by ruditimmermans**

### CODE REVIEW

**Review by jenspfahl — COMMENTED** [review]
Great, thanks for the translation work. Will review and merge this for the next release.

**Comment by ruditimmermans** [comment]
Ok thanks!

**Comment by jenspfahl** [comment]
Hey, i am integrating your translation and it looks good so far.
One thing i need to get translated for the language options:
 ` <string name="language_nl">Dutch</string>`
Thanks!

**Comment by ruditimmermans** [comment]
Hi,

Here you go:

 <string name="language_nl">Nederlands</string>

Thanks!

**Comment by jenspfahl** [comment]
Hey @ruditimmermans , could you please translate a few new strings for the next release to Dutch? I'll integrate your translations directly. Thanks!
```
  <string name="error_not_an_email_address">This field does not contain a valid email address.</string>
  <string name="title_delete_username_template">Delete Username Template</string>
  <string name="message_delete_username_template">Are you sure deleting username template \'%1$s\'? It wont be visible anymore in the username suggestions.</string>
  <string name="title_activity_list_username_templates">Templates for usernames</string>
  <string name="action_username_templates">Username templates</string>
  <string name="username_template_data_params">Define the username of a template and an optional description. The username is used to present suggestions for usernames when editing credentials.</string>
 
  <string name="title_new_username_template">New username template</string>
  <string name="title_change_username_template">Edit username template</string>
  <string name="hint_edit_username_template_username">Username</string>
  <string name="hint_edit_username_template_description">Additional description</string>

  <string name="whats_new_in_1_9">What\'s new in version 1.9</string>
  <string name="whats_new_in_1_9_bullet_1_head">Templates for frequent usernames</string>
  <string name="whats_new_in_1_9_bullet_1_text">With this new feature you can define your most used usernames being auto-suggested when creating new credentials. It also supports usernames as generic email aliases, if you want to use different aliases for your accounts.</string>
  <string name="whats_new_in_1_9_bullet_2_head">Custom CSV credential importer</string>
  <string name="whats_new_in_1_9_bullet_2_text">Although the \'Import Credentials From File\' - option supports a variety of CSV formats, like for Keepass and Bitwarden, you might encounter unsupported CSV formats. If so, you can define a custom format by assigning the CSV columns to the right credential field.</string>
  <string name="whats_new_in_1_9_bullet_3_head">Quick Settings Tile to open the vault</string>
  <string name="whats_new_in_1_9_bullet_3_text">Now you can open the app directly from the Android Quick Settings panel. Just add the ANOTHERpass tile to the panel in the Android Settings.</string>
  <string name="whats_new_in_1_9_bullet_4_head">Adaptive launcher icon</string>
  <string name="whats_new_in_1_9_bullet_4_text">The launcher icon has been polished to support any scale and, even more important, support monochrone themes.</string>

 <string name="cannot_read_file">Cannot read this file</string>
 <string name="empty_csv_credentials">This CSV file seems empty or is not in CSV format</string>

 <string name="with_email_alias">Declare the username as email address with a generic alias part</string>
  <string name="title_username_email_alias">What is an email alias part?</string>
  <string name="message_username_email_alias">Some email providers like Gmail provide generic aliases using the plus notation. So the same email account can have various aliases by adding \'+ALIAS\' before the \'@\' (e.g. test+alias1@example.org). You can use these aliases as usernames of credentials to benefit from having separate email addresses per account.</string>
  <string name="username_template_list_type">with email alias</string>
  <string name="username_template_type_desc_from_credential_name">alias from credential name (e.g. test+github@example.org)</string>
  <string name="username_template_type_desc_random_word">alias from a random word (e.g. test+hiaw@example.org)</string>
  <string name="username_template_type_desc_both">provide both</string>
  <string name="open_vault">Open vault</string>

  <string name="define_columns_of_csv_file">Cannot load file or fields are missing? Define columns of the file manually.</string>
  <string name="not_a_csv_column">only letters, digits, dash and stroke are allowed</string>
  <string name="csv_column_title">CSV columns</string>
  <string name="csv_column_message">Open the CSV file to be imported and input the column names of the corresponding credential fields.</string>
  <string name="csv_column_message_suggested_columns">Check the extracted CSV columns of \'%1$s\' and copy them to the corresponding credential fields.</string>
  <string name="current_csv_columns">Extracted CSV columns</string>
  <string name="csv_column_credential_name">column for credential name</string>
  <string name="csv_column_credential_username">column for username</string>
  <string name="csv_column_credential_website">column for website url</string>
  <string name="csv_column_credential_password">column for password</string>
  <string name="csv_column_credential_expiry_date">column for expiry date</string>
  <string name="csv_column_credential_additional_info">column for additional information</string>
```

**Comment by ruditimmermans** [comment]
Ok no problem here you go....
[dutch.txt](https://github.com/jenspfahl/ANOTHERpass/files/13813753/dutch.txt)

**Comment by jenspfahl** [comment]
manually merged

**Pull request closed without merging**
